/**
 * Canonical machine-readable error codes used by daemon transport and CLI.
 *
 * Keep this list stable once released. Additive changes are preferred.
 */
export const ErrorCodes = {
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_EXISTS: 'SESSION_ALREADY_EXISTS',
  ADAPTER_NOT_AVAILABLE: 'ADAPTER_NOT_AVAILABLE',
  PERMISSION_TIMEOUT: 'PERMISSION_TIMEOUT',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  GIT_OPERATION_FAILED: 'GIT_OPERATION_FAILED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  DIRECTORY_NOT_FOUND: 'DIRECTORY_NOT_FOUND',
  DIRECTORY_NOT_REGISTERED: 'DIRECTORY_NOT_REGISTERED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_INPUT: 'INVALID_INPUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  INVALID_JSON: 'INVALID_JSON',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  EMPTY_PROMPT: 'EMPTY_PROMPT',
  DISCOVERED_SESSION_NOT_FOUND: 'DISCOVERED_SESSION_NOT_FOUND',
  SESSION_NOT_RESUMABLE: 'SESSION_NOT_RESUMABLE',
  HOOK_REQUEST_NOT_FOUND: 'HOOK_REQUEST_NOT_FOUND',
  MISSING_REQUEST_ID: 'MISSING_REQUEST_ID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
