import { describe, expect, it } from 'vitest';
import { workflowActionProposalDigest } from '../../src/workflows/action-digest.js';
import type { WorkflowActionNode } from '../../src/workflows/types.js';

describe('workflow action proposal digest', () => {
  it('binds sanitized rendered side-effect inputs with a stable cross-runtime vector', () => {
    const node: WorkflowActionNode = {
      type: 'action',
      adapter: 'github',
      action: 'pull_request.create',
      requiresApproval: true,
    };

    expect(
      workflowActionProposalDigest(node, {
        idempotencyKey: 'pr:PAY-1842',
        input: {
          title: 'Fix PAY-1842',
          body: 'Generated by Viewport workflow.',
          token: 'runner-secret',
        },
      }),
    ).toBe('sha256:53887923b29799042301d48dd6298901190bf5e19f9fa03847a04c62a807c1e5');
  });
});
